version: "3.9"

services:
  backend:
    build: .
    container_name: ocean_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://ocean:ocean2025@db:5432/oceandb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ocean_db
    restart: always
    environment:
      POSTGRES_USER: ocean
      POSTGRES_PASSWORD: ocean2025
      POSTGRES_DB: oceandb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
