from app.models.rol import Rol
from app.models.usuario import Usuario
from app.models.conductor import Conductor
from app.models.vehiculo import Vehiculo
from app.models.trailer import Trailer
from app.models.comprador import Comprador
from app.models.destino import Destino
from app.models.origen import Origen
from app.models.patio import Patio
from app.models.factura import Factura
from app.models.tipo_entidad import TipoEntidad
from app.models.entidad import Entidad
from app.models.tipo_producto import TipoProducto
from app.models.unidad_medida import UnidadMedida
from app.models.proceso_producto import ProcesoProducto
from app.models.producto import Producto
from app.models.tipo_registro import TipoRegistro
from app.models.transportadora import Transportadora
from app.models.registro import Registro
from app.models.historial import Historial