from sqlalchemy import Column, Integer, String, Date, Time, ForeignKey
from sqlalchemy.orm import relationship
from app.config.database import Base

class Registro(Base):
    __tablename__ = "registro"

    id = Column(Integer, primary_key=True, index=True)
    tipo_id = Column(Integer, ForeignKey("tipo_registro.id"), nullable=False)
    fecha_entrada = Column(Date, nullable=True)
    hora_entrada = Column(Time, nullable=True)
    fecha_salida = Column(Date, nullable=True)
    hora_salida = Column(Time, nullable=True)
    vehiculo_id = Column(Integer, ForeignKey("vehiculo.id"), nullable=True)
    trailer_id = Column(Integer, ForeignKey("trailer.id"), nullable=True)
    conductor_id = Column(Integer, ForeignKey("conductor.id"), nullable=True)
    entidad_id = Column(Integer, ForeignKey("entidad.id"), nullable=True)
    producto_id = Column(Integer, ForeignKey("producto.id"), nullable=True)
    cantidad = Column(Integer, nullable=True)
    comprador_id = Column(Integer, ForeignKey("comprador.id"), nullable=True)
    transportadora_id = Column(Integer, ForeignKey("transportadora.id"), nullable=True)
    orden = Column(String, nullable=True)
    precinto = Column(String, nullable=True)
    origen_id = Column(Integer, ForeignKey("origen.id"), nullable=True)
    destino_id = Column(Integer, ForeignKey("destino.id"), nullable=True)
    patio_id = Column(Integer, ForeignKey("patio.id"), nullable=True)
    factura_id = Column(Integer, ForeignKey("factura.id"), nullable=True)
    peso_bruto = Column(Integer, nullable=True)
    peso_tara = Column(Integer, nullable=True)
    peso_neto = Column(Integer, nullable=True)
    estado = Column(Integer, nullable=True)
    observaciones = Column(String, nullable=True)
    consecutivo = Column(Integer, nullable=True)
    tiquete = Column(Integer, nullable=True)

    tipo = relationship("TipoRegistro", back_populates="registros")
    vehiculo = relationship("Vehiculo", back_populates="registros")
    trailer = relationship("Trailer", back_populates="registros")
    conductor = relationship("Conductor", back_populates="registros")
    entidad = relationship("Entidad", back_populates="registros")
    producto = relationship("Producto", back_populates="registros")
    comprador = relationship("Comprador", back_populates="registros")
    transportadora = relationship("Transportadora", back_populates="registros")
    origen = relationship("Origen", back_populates="registros")
    destino = relationship("Destino", back_populates="registros")
    patio = relationship("Patio", back_populates="registros")
    factura = relationship("Factura", back_populates="registros")
    historial = relationship("Historial", back_populates="registro")