"""inicial

Revision ID: 738f60e0eb4f
Revises: 
Create Date: 2026-05-21 15:02:52.338391

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '738f60e0eb4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('estado_sync')

    # ── PASO 1: Quitar TODAS las FKs ──────────────────────────────────────
    op.drop_constraint('fk_usuario_rol', 'usuario', type_='foreignkey')
    op.drop_constraint('entidad_ent_idtipoentidad_fkey', 'entidad', type_='foreignkey')
    op.drop_constraint('producto_prod_idtipoproducto_fkey', 'producto', type_='foreignkey')
    op.drop_constraint('producto_prod_idprocesoproducto_fkey', 'producto', type_='foreignkey')
    op.drop_constraint('producto_prod_idunidadmedida_fkey', 'producto', type_='foreignkey')
    op.drop_constraint('registro_reg_identidad_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idtipo_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idtrailer_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idpatio_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idtransportadora_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idvehiculo_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idconductor_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idfactura_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idcomprador_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_iddestino_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idproducto_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('registro_reg_idorigen_fkey', 'registro', type_='foreignkey')
    op.drop_constraint('fk_historial_usuario', 'historial', type_='foreignkey')
    op.drop_constraint('fk_historial_registro', 'historial', type_='foreignkey')

    # ── PASO 2: Migrar cada tabla ──────────────────────────────────────────

    # ROL
    op.add_column('rol', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('rol', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE rol SET id=rol_id, nombre=rol_nombre')
    op.alter_column('rol', 'id', nullable=False)
    op.alter_column('rol', 'nombre', nullable=False)
    op.drop_index('ix_rol_role_id', table_name='rol')
    op.create_index('ix_rol_id', 'rol', ['id'], unique=False)
    op.execute('ALTER TABLE rol DROP CONSTRAINT IF EXISTS rol_pkey')
    op.drop_column('rol', 'rol_id')
    op.drop_column('rol', 'rol_nombre')
    op.execute('ALTER TABLE rol ADD PRIMARY KEY (id)')

    # TIPO ENTIDAD
    op.add_column('tipo_entidad', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('tipo_entidad', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE tipo_entidad SET id=tpent_id, nombre=tpent_nombre')
    op.alter_column('tipo_entidad', 'id', nullable=False)
    op.alter_column('tipo_entidad', 'nombre', nullable=False)
    op.drop_index('ix_tipo_entidad_tpent_id', table_name='tipo_entidad')
    op.create_index('ix_tipo_entidad_id', 'tipo_entidad', ['id'], unique=False)
    op.execute('ALTER TABLE tipo_entidad DROP CONSTRAINT IF EXISTS tipo_entidad_pkey')
    op.drop_column('tipo_entidad', 'tpent_id')
    op.drop_column('tipo_entidad', 'tpent_nombre')
    op.execute('ALTER TABLE tipo_entidad ADD PRIMARY KEY (id)')

    # TIPO PRODUCTO
    op.add_column('tipo_producto', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('tipo_producto', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE tipo_producto SET id=tprod_id, nombre=tprod_nombre')
    op.alter_column('tipo_producto', 'id', nullable=False)
    op.alter_column('tipo_producto', 'nombre', nullable=False)
    op.drop_index('ix_tipo_producto_tprod_id', table_name='tipo_producto')
    op.create_index('ix_tipo_producto_id', 'tipo_producto', ['id'], unique=False)
    op.execute('ALTER TABLE tipo_producto DROP CONSTRAINT IF EXISTS tipo_producto_pkey')
    op.drop_column('tipo_producto', 'tprod_id')
    op.drop_column('tipo_producto', 'tprod_nombre')
    op.execute('ALTER TABLE tipo_producto ADD PRIMARY KEY (id)')

    # TIPO REGISTRO
    op.add_column('tipo_registro', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('tipo_registro', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE tipo_registro SET id=tr_id, nombre=tr_nombre')
    op.alter_column('tipo_registro', 'id', nullable=False)
    op.alter_column('tipo_registro', 'nombre', nullable=False)
    op.drop_index('ix_tipo_registro_tr_id', table_name='tipo_registro')
    op.create_index('ix_tipo_registro_id', 'tipo_registro', ['id'], unique=False)
    op.execute('ALTER TABLE tipo_registro DROP CONSTRAINT IF EXISTS tipo_registro_pkey')
    op.drop_column('tipo_registro', 'tr_id')
    op.drop_column('tipo_registro', 'tr_nombre')
    op.execute('ALTER TABLE tipo_registro ADD PRIMARY KEY (id)')

    # PROCESO PRODUCTO
    op.add_column('proceso_producto', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('proceso_producto', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE proceso_producto SET id=pp_id, nombre=pp_nombre')
    op.alter_column('proceso_producto', 'id', nullable=False)
    op.alter_column('proceso_producto', 'nombre', nullable=False)
    op.drop_index('ix_proceso_producto_pp_id', table_name='proceso_producto')
    op.create_index('ix_proceso_producto_id', 'proceso_producto', ['id'], unique=False)
    op.execute('ALTER TABLE proceso_producto DROP CONSTRAINT IF EXISTS proceso_producto_pkey')
    op.drop_column('proceso_producto', 'pp_id')
    op.drop_column('proceso_producto', 'pp_nombre')
    op.execute('ALTER TABLE proceso_producto ADD PRIMARY KEY (id)')

    # UNIDAD MEDIDA
    op.add_column('unidad_medida', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('unidad_medida', sa.Column('nombre', sa.String(), nullable=True))
    op.execute('UPDATE unidad_medida SET id=um_id, nombre=um_nombre')
    op.alter_column('unidad_medida', 'id', nullable=False)
    op.alter_column('unidad_medida', 'nombre', nullable=False)
    op.drop_index('ix_unidad_medida_um_id', table_name='unidad_medida')
    op.create_index('ix_unidad_medida_id', 'unidad_medida', ['id'], unique=False)
    op.execute('ALTER TABLE unidad_medida DROP CONSTRAINT IF EXISTS unidad_medida_pkey')
    op.drop_column('unidad_medida', 'um_id')
    op.drop_column('unidad_medida', 'um_nombre')
    op.execute('ALTER TABLE unidad_medida ADD PRIMARY KEY (id)')

    # USUARIO
    op.add_column('usuario', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('correo', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('clave', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('rol_id', sa.Integer(), nullable=True))
    op.execute('UPDATE usuario SET id=usuario_id, nombre=usuario_nombre, correo=usuario_correo, clave=usuario_clave, rol_id=usuario_idrol')
    op.alter_column('usuario', 'id', nullable=False)
    op.alter_column('usuario', 'nombre', nullable=False)
    op.alter_column('usuario', 'clave', nullable=False)
    op.alter_column('usuario', 'rol_id', nullable=False)
    op.drop_constraint('usuarios_usuario_correo_key', 'usuario', type_='unique')
    op.create_index('ix_usuario_id', 'usuario', ['id'], unique=False)
    op.execute('ALTER TABLE usuario DROP CONSTRAINT IF EXISTS usuario_pkey')
    op.drop_column('usuario', 'usuario_id')
    op.drop_column('usuario', 'usuario_nombre')
    op.drop_column('usuario', 'usuario_correo')
    op.drop_column('usuario', 'usuario_clave')
    op.drop_column('usuario', 'usuario_idrol')
    op.execute('ALTER TABLE usuario ADD PRIMARY KEY (id)')

    # COMPRADOR
    op.add_column('comprador', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('comprador', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('comprador', sa.Column('nit', sa.String(), nullable=True))
    op.add_column('comprador', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('comprador', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE comprador SET id=comp_id, nombre=comp_nombre, nit=comp_nit, telefono=comp_telefono, codigo=comp_codigo')
    op.alter_column('comprador', 'id', nullable=False)
    op.alter_column('comprador', 'nombre', nullable=False)
    op.drop_index('ix_comprador_comp_id', table_name='comprador')
    op.create_index('ix_comprador_id', 'comprador', ['id'], unique=False)
    op.execute('ALTER TABLE comprador DROP CONSTRAINT IF EXISTS comprador_pkey')
    op.drop_column('comprador', 'comp_id')
    op.drop_column('comprador', 'comp_nit')
    op.drop_column('comprador', 'comp_telefono')
    op.drop_column('comprador', 'comp_codigo')
    op.drop_column('comprador', 'comp_nombre')
    op.execute('ALTER TABLE comprador ADD PRIMARY KEY (id)')

    # CONDUCTOR
    op.add_column('conductor', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('conductor', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('conductor', sa.Column('cedula', sa.String(), nullable=True))
    op.add_column('conductor', sa.Column('telefono', sa.String(), nullable=True))
    op.execute('UPDATE conductor SET id=conduct_id, nombre=conduct_nombre, cedula=conduct_cedula, telefono=conduct_telefono')
    op.alter_column('conductor', 'id', nullable=False)
    op.alter_column('conductor', 'nombre', nullable=False)
    op.drop_index('ix_conductor_conduct_id', table_name='conductor')
    op.create_index('ix_conductor_id', 'conductor', ['id'], unique=False)
    op.execute('ALTER TABLE conductor DROP CONSTRAINT IF EXISTS conductor_pkey')
    op.drop_column('conductor', 'conduct_id')
    op.drop_column('conductor', 'conduct_nombre')
    op.drop_column('conductor', 'conduct_cedula')
    op.drop_column('conductor', 'conduct_telefono')
    op.execute('ALTER TABLE conductor ADD PRIMARY KEY (id)')

    # VEHICULO
    op.add_column('vehiculo', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('vehiculo', sa.Column('placa', sa.String(length=10), nullable=True))
    op.execute('UPDATE vehiculo SET id=vehi_id, placa=vehi_placa')
    op.alter_column('vehiculo', 'id', nullable=False)
    op.alter_column('vehiculo', 'placa', nullable=False)
    op.drop_index('ix_vehiculo_vehi_id', table_name='vehiculo')
    op.create_index('ix_vehiculo_id', 'vehiculo', ['id'], unique=False)
    op.execute('ALTER TABLE vehiculo DROP CONSTRAINT IF EXISTS vehiculo_pkey')
    op.drop_column('vehiculo', 'vehi_id')
    op.drop_column('vehiculo', 'vehi_placa')
    op.execute('ALTER TABLE vehiculo ADD PRIMARY KEY (id)')

    # TRAILER
    op.add_column('trailer', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('trailer', sa.Column('placa', sa.String(), nullable=True))
    op.execute('UPDATE trailer SET id=trai_id, placa=trai_placa')
    op.alter_column('trailer', 'id', nullable=False)
    op.alter_column('trailer', 'placa', nullable=False)
    op.drop_index('ix_trailer_trai_id', table_name='trailer')
    op.create_index('ix_trailer_id', 'trailer', ['id'], unique=False)
    op.execute('ALTER TABLE trailer DROP CONSTRAINT IF EXISTS trailer_pkey')
    op.drop_column('trailer', 'trai_id')
    op.drop_column('trailer', 'trai_placa')
    op.execute('ALTER TABLE trailer ADD PRIMARY KEY (id)')

    # TRANSPORTADORA
    op.add_column('transportadora', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('transportadora', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('transportadora', sa.Column('ciudad', sa.String(), nullable=True))
    op.add_column('transportadora', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('transportadora', sa.Column('nit', sa.String(), nullable=True))
    op.add_column('transportadora', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('transportadora', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE transportadora SET id=trans_id, nombre=trans_nombre, ciudad=trans_ciudad, direccion=trans_direccion, nit=trans_nit, telefono=trans_telefono, codigo=trans_codigo')
    op.alter_column('transportadora', 'id', nullable=False)
    op.alter_column('transportadora', 'nombre', nullable=False)
    op.drop_index('ix_transportadora_trans_id', table_name='transportadora')
    op.create_index('ix_transportadora_id', 'transportadora', ['id'], unique=False)
    op.execute('ALTER TABLE transportadora DROP CONSTRAINT IF EXISTS transportadora_pkey')
    op.drop_column('transportadora', 'trans_id')
    op.drop_column('transportadora', 'trans_nombre')
    op.drop_column('transportadora', 'trans_ciudad')
    op.drop_column('transportadora', 'trans_direccion')
    op.drop_column('transportadora', 'trans_nit')
    op.drop_column('transportadora', 'trans_telefono')
    op.drop_column('transportadora', 'trans_codigo')
    op.execute('ALTER TABLE transportadora ADD PRIMARY KEY (id)')

    # DESTINO
    op.add_column('destino', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('destino', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('destino', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE destino SET id=dest_id, nombre=dest_nombre, codigo=dest_codigo')
    op.alter_column('destino', 'id', nullable=False)
    op.alter_column('destino', 'nombre', nullable=False)
    op.drop_index('ix_destino_dest_id', table_name='destino')
    op.create_index('ix_destino_id', 'destino', ['id'], unique=False)
    op.execute('ALTER TABLE destino DROP CONSTRAINT IF EXISTS destino_pkey')
    op.drop_column('destino', 'dest_id')
    op.drop_column('destino', 'dest_nombre')
    op.drop_column('destino', 'dest_codigo')
    op.execute('ALTER TABLE destino ADD PRIMARY KEY (id)')

    # ORIGEN
    op.add_column('origen', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('origen', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('origen', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE origen SET id=ori_id, nombre=ori_nombre, codigo=ori_codigo')
    op.alter_column('origen', 'id', nullable=False)
    op.alter_column('origen', 'nombre', nullable=False)
    op.drop_index('ix_origen_ori_id', table_name='origen')
    op.create_index('ix_origen_id', 'origen', ['id'], unique=False)
    op.execute('ALTER TABLE origen DROP CONSTRAINT IF EXISTS origen_pkey')
    op.drop_column('origen', 'ori_id')
    op.drop_column('origen', 'ori_nombre')
    op.drop_column('origen', 'ori_codigo')
    op.execute('ALTER TABLE origen ADD PRIMARY KEY (id)')

    # PATIO
    op.add_column('patio', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('patio', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('patio', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE patio SET id=pat_id, nombre=pat_nombre, codigo=pat_codigo')
    op.alter_column('patio', 'id', nullable=False)
    op.alter_column('patio', 'nombre', nullable=False)
    op.drop_index('ix_patio_pat_id', table_name='patio')
    op.create_index('ix_patio_id', 'patio', ['id'], unique=False)
    op.execute('ALTER TABLE patio DROP CONSTRAINT IF EXISTS patio_pkey')
    op.drop_column('patio', 'pat_id')
    op.drop_column('patio', 'pat_nombre')
    op.drop_column('patio', 'pat_codigo')
    op.execute('ALTER TABLE patio ADD PRIMARY KEY (id)')

    # FACTURA
    op.add_column('factura', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('factura', sa.Column('fecha', sa.String(), nullable=True))
    op.execute('UPDATE factura SET id=fac_id, fecha=fac_fecha')
    op.alter_column('factura', 'id', nullable=False)
    op.alter_column('factura', 'fecha', nullable=False)
    op.drop_index('ix_factura_fac_id', table_name='factura')
    op.create_index('ix_factura_id', 'factura', ['id'], unique=False)
    op.execute('ALTER TABLE factura DROP CONSTRAINT IF EXISTS factura_pkey')
    op.drop_column('factura', 'fac_id')
    op.drop_column('factura', 'fac_fecha')
    op.execute('ALTER TABLE factura ADD PRIMARY KEY (id)')

    # ENTIDAD
    op.add_column('entidad', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('entidad', sa.Column('tipo_id', sa.Integer(), nullable=True))
    op.add_column('entidad', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('entidad', sa.Column('nit', sa.String(), nullable=True))
    op.add_column('entidad', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('entidad', sa.Column('codigo', sa.String(), nullable=True))
    op.execute('UPDATE entidad SET id=ent_id, tipo_id=ent_idtipoentidad, nombre=ent_nombre, nit=ent_nit, telefono=ent_telefono, codigo=ent_codigo')
    op.alter_column('entidad', 'id', nullable=False)
    op.alter_column('entidad', 'tipo_id', nullable=False)
    op.alter_column('entidad', 'nombre', nullable=False)
    op.drop_index('ix_entidad_ent_id', table_name='entidad')
    op.create_index('ix_entidad_id', 'entidad', ['id'], unique=False)
    op.execute('ALTER TABLE entidad DROP CONSTRAINT IF EXISTS entidad_pkey')
    op.drop_column('entidad', 'ent_id')
    op.drop_column('entidad', 'ent_idtipoentidad')
    op.drop_column('entidad', 'ent_nombre')
    op.drop_column('entidad', 'ent_nit')
    op.drop_column('entidad', 'ent_telefono')
    op.drop_column('entidad', 'ent_codigo')
    op.execute('ALTER TABLE entidad ADD PRIMARY KEY (id)')

    # PRODUCTO
    op.add_column('producto', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('producto', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('producto', sa.Column('codigo', sa.String(), nullable=True))
    op.add_column('producto', sa.Column('unidad_medida_id', sa.Integer(), nullable=True))
    op.add_column('producto', sa.Column('tipo_producto_id', sa.Integer(), nullable=True))
    op.add_column('producto', sa.Column('proceso_producto_id', sa.Integer(), nullable=True))
    op.execute('UPDATE producto SET id=prod_id, nombre=prod_nombre, codigo=prod_codigo, unidad_medida_id=prod_idunidadmedida, tipo_producto_id=prod_idtipoproducto, proceso_producto_id=prod_idprocesoproducto')
    op.alter_column('producto', 'id', nullable=False)
    op.alter_column('producto', 'nombre', nullable=False)
    op.alter_column('producto', 'unidad_medida_id', nullable=False)
    op.alter_column('producto', 'tipo_producto_id', nullable=False)
    op.alter_column('producto', 'proceso_producto_id', nullable=False)
    op.drop_index('ix_producto_prod_id', table_name='producto')
    op.create_index('ix_producto_id', 'producto', ['id'], unique=False)
    op.execute('ALTER TABLE producto DROP CONSTRAINT IF EXISTS producto_pkey')
    op.drop_column('producto', 'prod_id')
    op.drop_column('producto', 'prod_nombre')
    op.drop_column('producto', 'prod_codigo')
    op.drop_column('producto', 'prod_idunidadmedida')
    op.drop_column('producto', 'prod_idtipoproducto')
    op.drop_column('producto', 'prod_idprocesoproducto')
    op.execute('ALTER TABLE producto ADD PRIMARY KEY (id)')

    # REGISTRO
    op.add_column('registro', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('tipo_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('fecha_entrada', sa.Date(), nullable=True))
    op.add_column('registro', sa.Column('hora_entrada', sa.Time(), nullable=True))
    op.add_column('registro', sa.Column('fecha_salida', sa.Date(), nullable=True))
    op.add_column('registro', sa.Column('hora_salida', sa.Time(), nullable=True))
    op.add_column('registro', sa.Column('vehiculo_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('trailer_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('conductor_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('entidad_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('producto_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('comprador_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('transportadora_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('orden', sa.String(), nullable=True))
    op.add_column('registro', sa.Column('precinto', sa.String(), nullable=True))
    op.add_column('registro', sa.Column('origen_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('destino_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('patio_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('factura_id', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('peso_bruto', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('peso_tara', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('peso_neto', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('estado', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('observaciones', sa.String(), nullable=True))
    op.add_column('registro', sa.Column('consecutivo', sa.Integer(), nullable=True))
    op.add_column('registro', sa.Column('tiquete', sa.Integer(), nullable=True))
    op.execute('''UPDATE registro SET
        id=reg_id, tipo_id=reg_idtipo,
        fecha_entrada=reg_fechaentrada, hora_entrada=reg_horaentrada,
        fecha_salida=reg_fechasalida, hora_salida=reg_horasalida,
        vehiculo_id=reg_idvehiculo, trailer_id=reg_idtrailer,
        conductor_id=reg_idconductor, entidad_id=reg_identidad,
        producto_id=reg_idproducto, cantidad=reg_cantidad,
        comprador_id=reg_idcomprador, transportadora_id=reg_idtransportadora,
        orden=reg_orden, precinto=reg_precinto,
        origen_id=reg_idorigen, destino_id=reg_iddestino,
        patio_id=reg_idpatio, factura_id=reg_idfactura,
        peso_bruto=reg_pesobruto, peso_tara=reg_pesotara,
        peso_neto=reg_pesoneto, estado=reg_estado,
        observaciones=reg_observaciones, consecutivo=reg_consecutivo,
        tiquete=reg_tiquete
    ''')
    op.alter_column('registro', 'id', nullable=False)
    op.alter_column('registro', 'tipo_id', nullable=False)
    op.drop_index('idx_reg_idcomprador', table_name='registro')
    op.drop_index('idx_reg_idconductor', table_name='registro')
    op.drop_index('idx_reg_iddestino', table_name='registro')
    op.drop_index('idx_reg_identidad', table_name='registro')
    op.drop_index('idx_reg_idfactura', table_name='registro')
    op.drop_index('idx_reg_idorigen', table_name='registro')
    op.drop_index('idx_reg_idpatio', table_name='registro')
    op.drop_index('idx_reg_idproducto', table_name='registro')
    op.drop_index('idx_reg_idtipo', table_name='registro')
    op.drop_index('idx_reg_idtrailer', table_name='registro')
    op.drop_index('idx_reg_idtransportadora', table_name='registro')
    op.drop_index('idx_reg_idvehiculo', table_name='registro')
    op.drop_index('idx_tipo_fecha_salida', table_name='registro')
    op.drop_index('ix_registro_reg_id', table_name='registro')
    op.create_index('ix_registro_id', 'registro', ['id'], unique=False)
    op.execute('ALTER TABLE registro DROP CONSTRAINT IF EXISTS registro_pkey')
    op.drop_column('registro', 'reg_id')
    op.drop_column('registro', 'reg_idtipo')
    op.drop_column('registro', 'reg_fechaentrada')
    op.drop_column('registro', 'reg_horaentrada')
    op.drop_column('registro', 'reg_fechasalida')
    op.drop_column('registro', 'reg_horasalida')
    op.drop_column('registro', 'reg_idvehiculo')
    op.drop_column('registro', 'reg_idtrailer')
    op.drop_column('registro', 'reg_idconductor')
    op.drop_column('registro', 'reg_identidad')
    op.drop_column('registro', 'reg_idproducto')
    op.drop_column('registro', 'reg_cantidad')
    op.drop_column('registro', 'reg_idcomprador')
    op.drop_column('registro', 'reg_idtransportadora')
    op.drop_column('registro', 'reg_orden')
    op.drop_column('registro', 'reg_precinto')
    op.drop_column('registro', 'reg_idorigen')
    op.drop_column('registro', 'reg_iddestino')
    op.drop_column('registro', 'reg_idpatio')
    op.drop_column('registro', 'reg_idfactura')
    op.drop_column('registro', 'reg_pesobruto')
    op.drop_column('registro', 'reg_pesotara')
    op.drop_column('registro', 'reg_pesoneto')
    op.drop_column('registro', 'reg_estado')
    op.drop_column('registro', 'reg_observaciones')
    op.drop_column('registro', 'reg_consecutivo')
    op.drop_column('registro', 'reg_tiquete')
    op.execute('ALTER TABLE registro ADD PRIMARY KEY (id)')

    # HISTORIAL
    op.add_column('historial', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('historial', sa.Column('accion', sa.String(), nullable=True))
    op.add_column('historial', sa.Column('fecha', sa.Date(), nullable=True))
    op.add_column('historial', sa.Column('hora', sa.Time(), nullable=True))
    op.add_column('historial', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('historial', sa.Column('registro_id', sa.Integer(), nullable=True))
    op.execute('UPDATE historial SET id=his_id, accion=his_accion, fecha=his_fecha, hora=his_hora, usuario_id=his_idusuario, registro_id=his_idregistro')
    op.alter_column('historial', 'id', nullable=False)
    op.alter_column('historial', 'accion', nullable=False)
    op.alter_column('historial', 'fecha', nullable=False)
    op.alter_column('historial', 'hora', nullable=False)
    op.alter_column('historial', 'usuario_id', nullable=False)
    op.alter_column('historial', 'registro_id', nullable=False)
    op.create_index('ix_historial_id', 'historial', ['id'], unique=False)
    op.execute('ALTER TABLE historial DROP CONSTRAINT IF EXISTS historial_pkey')
    op.drop_column('historial', 'his_id')
    op.drop_column('historial', 'his_accion')
    op.drop_column('historial', 'his_fecha')
    op.drop_column('historial', 'his_hora')
    op.drop_column('historial', 'his_idusuario')
    op.drop_column('historial', 'his_idregistro')
    op.execute('ALTER TABLE historial ADD PRIMARY KEY (id)')

    # ── PASO 3: Recrear TODAS las FKs ─────────────────────────────────────
    op.create_foreign_key(None, 'usuario', 'rol', ['rol_id'], ['id'])
    op.create_foreign_key(None, 'entidad', 'tipo_entidad', ['tipo_id'], ['id'])
    op.create_foreign_key(None, 'producto', 'unidad_medida', ['unidad_medida_id'], ['id'])
    op.create_foreign_key(None, 'producto', 'tipo_producto', ['tipo_producto_id'], ['id'])
    op.create_foreign_key(None, 'producto', 'proceso_producto', ['proceso_producto_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'tipo_registro', ['tipo_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'vehiculo', ['vehiculo_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'trailer', ['trailer_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'conductor', ['conductor_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'entidad', ['entidad_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'producto', ['producto_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'comprador', ['comprador_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'transportadora', ['transportadora_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'origen', ['origen_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'destino', ['destino_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'patio', ['patio_id'], ['id'])
    op.create_foreign_key(None, 'registro', 'factura', ['factura_id'], ['id'])
    op.create_foreign_key(None, 'historial', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'historial', 'registro', ['registro_id'], ['id'])


def downgrade() -> None:
    pass