// src/utils/transformarDatos.js

const transformarDatos = (data) => {
    return data.map((item) => ({
      registro_id: item.reg_id || "",
      tipo: item.tipo?.tr_nombre || "",
      consecutivo: item.reg_consecutivo || "",
      consecutivo_tiquete: item.reg_tiquete || "",
      vehiculo_placa: item.vehiculo?.vehi_placa || "",
      vehiculo_id: item.vehiculo?.vehi_id || "",
      conductor_cedula: item.conductor?.conduct_cedula || "",
      conductor_nombre: item.conductor?.conduct_nombre || "",
      conductor_id: item.conductor?.conduct_id || "",
      trailer_placa: item.trailer?.trai_placa || "",
      trailer_id: item.trailer?.trai_id || "",
      fecha_entrada: item.reg_fechaentrada || "",
      hora_entrada: item.reg_horaentrada || "",
      fecha_salida: item.reg_fechasalida || "",
      hora_salida: item.reg_horasalida || "",
      peso_bruto: item.reg_pesobruto || "",
      peso_tara: item.reg_pesotara || "",
      peso_neto: item.reg_pesoneto || "",
      factura_fecha: item.factura?.fac_fecha || "",
      factura_id: item.factura?.fac_id || "",
      observaciones: item.reg_observaciones || "",
      entidad_nombre: item.entidad?.ent_nombre || "",
      entidad_codigo: item.entidad?.ent_codigo || "",
      entidad_id: item.entidad?.ent_id || "",
      comprador_nombre: item.comprador?.comp_nombre || "",
      comprador_codigo: item.comprador?.comp_codigo || "",
      comprador_id: item.comprador?.comp_id || "",
      producto_nombre: item.producto?.prod_nombre || "",
      producto_codigo: item.producto?.prod_codigo || "",
      producto_id: item.producto?.prod_id || "",
      transportadora_nombre: item.transportadora?.trans_nombre || "",
      transportadora_id: item.transportadora?.trans_id || "",
      orden: item.reg_orden || "",
      precinto: item.reg_precinto || "",
      origen_nombre: item.origen?.ori_nombre || "",
      origen_codigo: item.origen?.ori_codigo || "",
      origen_id: item.origen?.ori_id || "",
      destino_nombre: item.destino?.dest_nombre || "",
      destino_codigo: item.destino?.dest_codigo || "",
      destino_id: item.destino?.dest_id || "",
      patio_nombre: item.patio?.pat_nombre || "",
      patio_codigo: item.patio?.pat_codigo || "",
      patio_id: item.patio?.pat_id || "",
      cantidad: item.reg_cantidad || "",
      unidad_medida: item.producto?.unidad_medida?.um_nombre || "",
    }));
  };
  
  export default transformarDatos;
  